apiVersion: v1
kind: Service
metadata:
    name: "kmac-da57"
    labels:
        app: "kmac-da57"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kmac-da57"