name: Create Archive

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'tar'
        filename: 'Source code.tar'
        exclusions: '.github'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "Source code.tar"
        token: ${{ secrets.GITHUB_TOKEN }}
